In [1]:
import pandas as pd

data = {
    "order_id":[101,102,103,104,105,106,107,108,109,110],
    "order_date":["2024-01-01","2024-01-02","2024-01-03","2024-01-04","2024-01-05",
                  "2024-01-06","2024-01-07","2024-01-08","2024-01-09","2024-01-10"],
    "customer_name":["Amit","Ravi","Sneha","Neha","Arjun","Pooja","Rahul","Simran","Karan","Anita"],
    "city":["Delhi","Jaipur","Delhi","Mumbai","Delhi","Jaipur","Mumbai","Delhi","Jaipur","Mumbai"],
    "product":["Laptop","Shirt","Mobile","Shoes","Tablet","Jeans","Laptop","Mobile","Shoes","T-shirt"],
    "category":["Electronics","Fashion","Electronics","Fashion","Electronics","Fashion","Electronics","Electronics","Fashion","Fashion"],
    "quantity":[1,2,1,3,1,2,1,2,1,3],
    "price":[50000,1000,20000,2000,30000,1500,55000,18000,2500,700],
    "status":["Completed","Completed","Cancelled","Completed","Completed","Completed","Completed","Completed","Cancelled","Completed"]
}

df = pd.DataFrame(data)
df.head()

,order_id,order_date,customer_name,city,product,category,quantity,price,status
0,101,2024-01-01,Amit,Delhi,Laptop,Electronics,1,50000,Completed
1,102,2024-01-02,Ravi,Jaipur,Shirt,Fashion,2,1000,Completed
2,103,2024-01-03,Sneha,Delhi,Mobile,Electronics,1,20000,Cancelled
3,104,2024-01-04,Neha,Mumbai,Shoes,Fashion,3,2000,Completed
4,105,2024-01-05,Arjun,Delhi,Tablet,Electronics,1,30000,Completed

In [2]:
df['total_sales']=df['quantity']*df['price']
df.head()

,order_id,order_date,customer_name,city,product,category,quantity,price,status,total_sales
0,101,2024-01-01,Amit,Delhi,Laptop,Electronics,1,50000,Completed,50000
1,102,2024-01-02,Ravi,Jaipur,Shirt,Fashion,2,1000,Completed,2000
2,103,2024-01-03,Sneha,Delhi,Mobile,Electronics,1,20000,Cancelled,20000
3,104,2024-01-04,Neha,Mumbai,Shoes,Fashion,3,2000,Completed,6000
4,105,2024-01-05,Arjun,Delhi,Tablet,Electronics,1,30000,Completed,30000

In [ ]:
# INSIGHTS

In [3]:
# 1.TOTAL REVENUE
print("total revenue:",df['total_sales'].sum())

total revenue: 206600

In [4]:
# 2.city wise sales
city_sales=(df.groupby('city')['total_sales'].sum())
print(city_sales)

city
Delhi     136000
Jaipur      7500
Mumbai     63100
Name: total_sales, dtype: int64

In [5]:
# 3.category-wise sales
category_sales=df.groupby('category')['total_sales'].sum()
print(category_sales)

category
Electronics    191000
Fashion         15600
Name: total_sales, dtype: int64

In [ ]:
# 4.top products sold
top_products=df.groupby('product')['quantity'].sum().sort_values(ascending=False)
print(top_products)

product
Shoes      4
T-shirt    3
Mobile     3
Laptop     2
Jeans      2
Shirt      2
Tablet     1
Name: quantity, dtype: int64

In [ ]:
# 5.cancelled order and completed order
print(df['status'].value_counts())

status
Completed    8
Cancelled    2
Name: count, dtype: int64

In [ ]:
# 6.highest sales according to city
df.groupby('city')['total_sales'].sum().sort_values(ascending=False)

city
Delhi     136000
Mumbai     63100
Jaipur      7500
Name: total_sales, dtype: int64

In [ ]:
# 7.highest revenue by product
df.groupby('product')['total_sales'].sum().sort_values(ascending=False)

product
Laptop     105000
Mobile      56000
Tablet      30000
Shoes        8500
Jeans        3000
T-shirt      2100
Shirt        2000
Name: total_sales, dtype: int64

In [9]:
# 8.LOSS BY CANCELLED ORDERS
df[df['status'] == 'Cancelled']['total_sales'].sum()

np.int64(22500)

In [ ]:
# 9.daily sales trend
df.groupby('order_date')['total_sales'].sum()

order_date
2024-01-01    50000
2024-01-02     2000
2024-01-03    20000
2024-01-04     6000
2024-01-05    30000
2024-01-06     3000
2024-01-07    55000
2024-01-08    36000
2024-01-09     2500
2024-01-10     2100
Name: total_sales, dtype: int64

In [ ]:
# top 3 customers on revenue basis
df.groupby('customer_name')['total_sales'].sum().sort_values(ascending=False).head(3)

customer_name
Rahul     55000
Amit      50000
Simran    36000
Name: total_sales, dtype: int64

In [ ]:
df.groupby('city')['total_sales'].sum().sort_values(ascending=False)

city
Delhi     136000
Mumbai     63100
Jaipur      7500
Name: total_sales, dtype: int64

In [ ]:
df[df['status']=='cancelled']['total_sales'].sum()

np.int64(0)

In [ ]:
df.groupby('customer_name')['total_sales'].sum().sort_values(ascending=False).head(3)

customer_name
Rahul     55000
Amit      50000
Simran    36000
Name: total_sales, dtype: int64

In [ ]:
# percentage of cancelled orders
cancel_percent=(df['status'].value_counts(normalize=True)*100)
print(cancel_percent)

status
Completed    80.0
Cancelled    20.0
Name: proportion, dtype: float64

In [ ]:
## Key Insights

# - Delhi generated the highest revenue among all cities.
# - Rahul is the top customer contributing maximum sales.
# - Total loss due to cancelled orders is ₹22,500.
# - 20% of orders were cancelled, indicating a potential area for improvement.
# - Electronics category shows strong performance compared to others.